import SpotifyWrapper from 'spotify-wrapper';

const spotify = new SpotifyWrapper({
  token: 'BQCw5u9pY2G0nIqlz9G7N_e-5XjcYkW5Nis0SaphgRYkxldPpEQo-jRQ9OXExxVp9xrIA8gNLSnsc-pzdBGWFcnlTeaiYtfiuaOUE54b0pi9mGLGIaJTpDAIss7yBtTRXaJwftQkmhvnOmdhhKEyOTNuMw6ECUPmRlSC6N0FtONaBrseoQOazRsaYrQ4Yj6n0enH61AdL69mrvRkL_DQMMU5B-KCDwVnuXTWWK_EOrrTFyF8MIi71mlva1X1VLsYIy618w4XrHFOQQ',
});

export default spotify;
